name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout  ️
        uses: actions/checkout@v2.3.1

      - name: Install and Build   
        run: |
          yarn add node-sass
          yarn add sass --save-dev
          yarn install
          yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      # - name: Deploy  
      #   uses: JamesIves/github-pages-deploy-action@4.1.3
      #   with:
      #     BRANCH: gh-pages
      #     FOLDER: docs/.vuepress/dist
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Deploy
      	# 将构建产物 commit 到一个分支上，用于发布静态站点资源
      	# https://github.com/peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Github 会在 workflow 中自动生成 GIHUBT_TOKEN，用于认证 workflow 的运行
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 静态资源目录设置
          publish_dir: docs/.vuepress/dist
          # 默认发布到 gh-pages 分支上，可以指定特定的发布分支（不能选拉取代码的分支）
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}